# Generated by Django 6.0.1 on 2026-01-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'disponible'), ('on_route', 'en ruta'), ('maintenance', 'En mantenimiento')], default='available', max_length=20)),
            ],
        ),
    ]
